service: react-notes-app-api

# use serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: us-east-1
